stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install         
    - npm test             

deploy:
  stage: deploy
  only:
    - main  
  script:
    - npm install -g vercel  
    - vercel --confirm --prod  
  when: on_failure
 